# Generated by Django 3.2 on 2021-04-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=155, verbose_name='Titulo do Album')),
                ('data', models.DateField(auto_now=True, verbose_name='Data do Album')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome da Banda')),
            ],
            options={
                'verbose_name': 'banda',
                'verbose_name_plural': 'bandas',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=155, verbose_name='Titulo da musica')),
                ('segundos', models.IntegerField(verbose_name='Duração da Musica')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disco.album', verbose_name='Album da Musica')),
            ],
            options={
                'verbose_name': 'musica',
                'verbose_name_plural': 'musicas',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disco.banda', verbose_name='Banda do Album'),
        ),
    ]
